name: release windows

on:
  push:
    tags:
      - 'release-*'
      - 'v*'

jobs:
  build-windows-release:
    runs-on: windows-latest
  
    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Move to the parent directory and fetch dependencies
      - name: Fetch dependencies
        run: |
          cd ..
          mkdir lib
          cd lib
          git clone https://github.com/razterizer/Core.git
          git clone https://github.com/razterizer/Termin8or.git

      # Step 3: Build project
      - name: Run build.bat
        continue-on-error: false
        run: |
          cd $env:GITHUB_WORKSPACE\SurgSim_Lite
          ./build.bat
          
      # Step 4: List all files
      - name: Debug - List ALL files after build
        run: |
          cd $env:GITHUB_WORKSPACE
          echo "=== Full directory structure ==="
          Get-ChildItem -Recurse -File | Select-Object Name, Directory | Format-Table
          
      # Step 5: Prepare files for upload
      - name: Prepare files for upload
        run: |
          New-Item -ItemType Directory -Force -Path "upload-temp"
          Copy-Item "SurgSim_Lite/x64/Release/SurgSim_Lite.exe" "upload-temp/"
          Copy-Item "SurgSim_Lite/x64/Release/title.txt" "upload-temp/"
          if (Test-Path "SurgSim_Lite/x64/Release/fonts") {
              Copy-Item -Recurse "SurgSim_Lite/x64/Release/fonts" "upload-temp/"
          }

      # Step 6: Upload build artifact
      - name: Upload Windows build artifact
        uses: actions/upload-artifact@v4
        with:
          name: surgsim_lite-windows-build
          path: upload-temp/
          retention-days: 1

  create-windows-release:
    runs-on: windows-latest
    needs: build-windows-release
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Download Windows build artifact
        uses: actions/download-artifact@v4
        with:
          name: surgsim_lite-windows-build
          path: windows-build
          
      - name: Debug - List downloaded files
        run: |
          cd windows-build
          echo "=== Downloaded files ==="
          Get-ChildItem -Recurse
          
      - name: Create Windows distribution package
        run: |
          cd windows-build
          # Create a clean distribution folder
          New-Item -ItemType Directory -Force -Path "surgsim_lite-${{ github.ref_name }}"
          # Copy the executable and necessary files
          Copy-Item "SurgSim_Lite.exe" "surgsim_lite-${{ github.ref_name }}/"
          Copy-Item "title.txt" "surgsim_lite-${{ github.ref_name }}/"
          # Copy fonts directory (if it exists)
          if (Test-Path "fonts") {
            Copy-Item -Recurse "fonts" "surgsim_lite-${{ github.ref_name }}/"
          }
          # Create zip archive
          Compress-Archive -Path "surgsim_lite-${{ github.ref_name }}" -DestinationPath "surgsim_lite-${{ github.ref_name }}-windows.zip"
          
      - name: Upload Windows package to release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref_name }}  # Note: just the tag name, not refs/tags/
          artifacts: windows-build/surgsim_lite-${{ github.ref_name }}-windows.zip
          allowUpdates: true  # ← This is the key!
          body: ${{ github.event.release.body || github.event.head_commit.message }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


