name: release linux

on:
  push:
    tags:
      - 'release-*'
      - 'v*'

jobs:
  build-linux-release:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository.
      - name: Checkout repository
        uses: actions/checkout@v4
      
      # Step 2: Move to the parent directory and fetch dependencies.
      - name: Fetch dependencies
        run: |
          cd ..
          mkdir lib
          cd lib
          git clone https://github.com/razterizer/Core.git
          git clone https://github.com/razterizer/Termin8or.git
      
      # Step 3: Build project.
      - name: Build project
        run: |
          cd SurgSim_Lite
          ./build.sh
        continue-on-error: false

      # Step 4: Upload build artifact.
      - name: Upload Linux build artifact
        uses: actions/upload-artifact@v4
        with:
          name: surgsim_lite-glibc2.38
          path: SurgSim_Lite/bin/
          retention-days: 1

  build-legacy-linux-release:
    runs-on: ubuntu-22.04
    
    steps:
      # Step 1: Checkout the repository.
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Move to the parent directory and fetch dependencies.
      - name: Fetch dependencies
        run: |
          cd ..
          mkdir lib
          cd lib
          git clone https://github.com/razterizer/Core.git
          git clone https://github.com/razterizer/Termin8or.git

      # Step 3: Build project.
      - name: Build project
        run: |
          cd SurgSim_Lite
          ./build.sh
        continue-on-error: false

      # Step 4: Upload build artifact.
      - name: Upload Legacy Linux build artifact
        uses: actions/upload-artifact@v4
        with:
          name: surgsim_lite-glibc2.35
          path: SurgSim_Lite/bin/
          retention-days: 1

  create-linux-release:
    runs-on: ubuntu-latest
    needs: [build-linux-release, build-legacy-linux-release]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download GLIBC 2.38 build
        uses: actions/download-artifact@v4
        with:
          name: surgsim_lite-glibc2.38
          path: glibc2.38

      - name: Download GLIBC 2.35 build
        uses: actions/download-artifact@v4
        with:
          name: surgsim_lite-glibc2.35
          path: glibc2.35

      - name: Create combined Linux distribution package
        run: |
          mkdir surgsim_lite-${{ github.ref_name }}
          cp glibc2.38/surgsim_lite surgsim_lite-${{ github.ref_name }}/surgsim_lite-glibc2.38
          cp glibc2.35/surgsim_lite surgsim_lite-${{ github.ref_name }}/surgsim_lite-glibc2.35
          cp glibc2.38/title.txt surgsim_lite-${{ github.ref_name }}/
          if [ -d glibc2.38/fonts ]; then
            cp -r glibc2.38/fonts surgsim_lite-${{ github.ref_name }}/
          fi
          echo "This package contains two binaries:" > surgsim_lite-${{ github.ref_name }}/README.txt
          echo "- surgsim_lite-glibc2.38: for modern systems (Ubuntu 24.04+, Arch Linux)" >> surgsim_lite-${{ github.ref_name }}/README.txt
          echo "- surgsim_lite-glibc2.35: for legacy systems (WSL, Ubuntu 22.04)" >> surgsim_lite-${{ github.ref_name }}/README.txt
          echo "" >> surgsim_lite-${{ github.ref_name }}/README.txt
          echo "Run the binary that matches your system's glibc version." >> surgsim_lite-${{ github.ref_name }}/README.txt
          echo "" >> surgsim_lite-${{ github.ref_name }}/README.txt
          echo "To run either executable, you might have to first do:" >> surgsim_lite-${{ github.ref_name }}/README.txt
          echo "  chmod ugo+x surgsim_lite-glibc2.38" >> surgsim_lite-${{ github.ref_name }}/README.txt
          echo " or:" >> surgsim_lite-${{ github.ref_name }}/README.txt
          echo "  chmod ugo+x surgsim_lite-glibc2.35" >> surgsim_lite-${{ github.ref_name }}/README.txt
          tar -czf surgsim_lite-${{ github.ref_name }}-linux.tar.gz surgsim_lite-${{ github.ref_name }}/

      - name: Upload Linux package to release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref_name }}
          artifacts: surgsim_lite-${{ github.ref_name }}-linux.tar.gz
          allowUpdates: true
          body: ${{ github.event.release.body || github.event.head_commit.message }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
